config/routes.rb
IntensityJobs::Application.routes.draw do
  resources :contact_us

  get "home/sitemap"

  mount RailsAdminImport::Engine => '/rails_admin_import', as: 'rails_admin_import'
  mount RailsAdmin::Engine => '/leads', :as => 'rails_admin'
  
 devise_for :admins, controllers: { omniauth_callbacks: "admins/omniauth_callbacks" }

  resources :feed_schemas, only: [] do
    member do
      get :fetch_sample
    end
  end

  resources :jobs, only: [:index, :show, :new, :create] do
    member do
      get :apply
    end

    collection do
      get :feed
    end
  end

  resources :job_categories, only: :show do
    resources :jobs, only: [:index, :show]
  end

  root to: 'jobs#index'

end

app/models/contact_u.rb
class ContactU < ActiveRecord::Base
  attr_accessible :body, :email, :name
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  # GET /contact_us
  # GET /contact_us.json
  def index
    @contact_us = ContactU.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contact_us }
    end
  end

  # GET /contact_us/1
  # GET /contact_us/1.json
  def show
    @contact_u = ContactU.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact_u }
    end
  end

  # GET /contact_us/new
  # GET /contact_us/new.json
  def new
    @contact_u = ContactU.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact_u }
    end
  end

  # GET /contact_us/1/edit
  def edit
    @contact_u = ContactU.find(params[:id])
  end

  # POST /contact_us
  # POST /contact_us.json
  def create
    @contact_u = ContactU.new(params[:contact_u])

    respond_to do |format|
      if @contact_u.save
        format.html { redirect_to @contact_u, notice: 'Contact u was successfully created.' }
        format.json { render json: @contact_u, status: :created, location: @contact_u }
      else
        format.html { render action: "new" }
        format.json { render json: @contact_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contact_us/1
  # PUT /contact_us/1.json
  def update
    @contact_u = ContactU.find(params[:id])

    respond_to do |format|
      if @contact_u.update_attributes(params[:contact_u])
        format.html { redirect_to @contact_u, notice: 'Contact u was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_us/1
  # DELETE /contact_us/1.json
  def destroy
    @contact_u = ContactU.find(params[:id])
    @contact_u.destroy

    respond_to do |format|
      format.html { redirect_to contact_us_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/views/contact_us/_form.html.slim
= form_for @contact_u do |f|
  - if @contact_u.errors.any?
    #error_explanation
      h2 = "#{pluralize(@contact_u.errors.count, "error")} prohibited this contact_u from being saved:"
      ul
        - @contact_u.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :body
    = f.text_field :body
  .actions = f.submit 'Save'

app/views/contact_us/edit.html.slim
h1 Editing contact_u

== render 'form'

= link_to 'Show', @contact_u
'|
= link_to 'Back', contact_us_path

app/views/contact_us/index.html.slim
h1 Listing contact_us

table
  tr
    th Name
    th Email
    th Body
    th
    th
    th

  - @contact_us.each do |contact_u|
    tr
      td = contact_u.name
      td = contact_u.email
      td = contact_u.body
      td = link_to 'Show', contact_u
      td = link_to 'Edit', edit_contact_u_path(contact_u)
      td = link_to 'Destroy', contact_u, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Contact u', new_contact_u_path

app/views/contact_us/new.html.slim
h1 New contact_u

== render 'form'

= link_to 'Back', contact_us_path

app/views/contact_us/show.html.slim
p#notice = notice

p
  strong Name:
  = @contact_u.name
p
  strong Email:
  = @contact_u.email
p
  strong Body:
  = @contact_u.body

= link_to 'Edit', edit_contact_u_path(@contact_u)
'|
= link_to 'Back', contact_us_path