config/routes.rb
IntensityJobs::Application.routes.draw do
  resources :contact_us

  get "home/sitemap"

  mount RailsAdminImport::Engine => '/rails_admin_import', as: 'rails_admin_import'
  mount RailsAdmin::Engine => '/leads', :as => 'rails_admin'
  
 devise_for :admins, controllers: { omniauth_callbacks: "admins/omniauth_callbacks" }

  resources :feed_schemas, only: [] do
    member do
      get :fetch_sample
    end
  end

  resources :jobs, only: [:index, :show, :new, :create] do
    member do
      get :apply
    end

    collection do
      get :feed
    end
  end

  resources :job_categories, only: :show do
    resources :jobs, only: [:index, :show]
  end

  root to: 'jobs#index'

end

app/views/shared/_chitnka_ad.html.erb
<script src="http://f.adbull.com/1_78158.js"></script>

app/views/shared/_footer.html.erb
<!--  term and condition page, faq page, about us page -->
<footer role="site-footer">
  <div class="container">
    <ul class="footernav">
      <li><a href="#">Home</a></li>
      <li><a href="#">How dose it Works</a></li>
      <li><a href="#">Terms & Conditions</a></li>
      <li><a href="#">Faq</a></li>
      <li><a href="#">About us</a></li>

    </ul>

    <ul class="social">
      <li class="social-header"><span> Vist us : </span></li>
      <li class="facebook-panel"><a href="https://www.facebook.com/IntensityJob" target="_blank">facebook</a></li>
      <li class="googleplus-panel"><a href="https://plus.google.com/u/0/b/111354903294540833142/111354903294540833142" target="_blank">googleplus</a></li>
    </ul>
  </div>
</footer>

app/views/shared/_head.slim
link href="assets/ico/apple-touch-icon-144-precomposed.png" rel="apple-touch-icon-precomposed" sizes="144x144"
link href="assets/ico/apple-touch-icon-114-precomposed.png" rel="apple-touch-icon-precomposed" sizes="114x114"
link href="assets/ico/apple-touch-icon-72-precomposed.png" rel="apple-touch-icon-precomposed" sizes="72x72"
link href="assets/ico/apple-touch-icon-57-precomposed.png" rel="apple-touch-icon-precomposed"
link href="assets/ico/favicon.png" rel="shortcut icon"

app/views/shared/_job_categories.slim
.large-3.columns.job-category-wrapper
  .job-category
    h5 Filter jobs by category.
    ul.job-category-list
      - JobCategory.root_categories.each do |cat|
        li class=class_for_category(cat)
          = link_to cat.name, job_category_jobs_path(job_category_id: cat)

app/views/shared/_page_header.slim
header role="top-header"
  .navbar.navbar-fixed-top
    .navbar-inner
      .container
        /! .btn-navbar is used as the toggle for collapsed navbar content
        a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        /! Be sure to leave the brand out there if you want it shown
        = link_to 'Intensity Jobs', root_path, class: 'brand'
        /! Everything you want hidden at 940px or less, place within here
        .nav-collapse.collapse
          ul.nav
            li
              = link_to 'BROWSER JOBS', jobs_path
            li
              a href="#"
          ul.nav.pull-right
            li
              a href="#" CAREER ADVICE
            li
              a href="#" POST NEW JOB

app/views/shared/_site_meta.slim
meta charset="utf-8"
meta content="width=device-width, initial-scale=1.0" name="viewport"
meta content="IntensityJobs" name="author"
meta name="revisit-after" content="1 days"
meta name="ROBOTS" content="INDEX, FOLLOW"
meta name="description" content=page_meta_description
meta name="Keywords" content=page_meta_keywords

// alexa site verification code
meta name="alexaVerifyID" content="eEX6waT1JrNnhdnO4if9VhqOirA"
// bing verification code
meta name="msvalidate.01" content="379D48E60E81BD7556DB75DE8AA29A38"

// facebooks' tags
meta property="og:type" content="website"
meta property="og:description" content=page_meta_description
meta property="og:title" content=page_meta_title
meta property="og:url" content=page_meta_url

//twitter's tags
meta name="twitter:card" content=page_meta_description
meta name="twitter:title" content=page_meta_title
meta name="twitter:url" content=page_meta_url
meta name="twitter:description" content=page_meta_description

// google + tags
meta itemprop="name" content=page_meta_title
meta itemprop="description" content=page_meta_description
meta itemprop="image" content=""
meta name="google-site-verification" content="R_fUnFzbqbuz7OV9yLnYv8MGpiixsOT5GDaLsrCrCmY"
= yield :page_meta if content_for?(:page_meta)
= auto_discovery_link_tag(:atom, feed_jobs_url(format: 'atom'))

app/views/shared/_social_tabs.slim
javascript:
  $("#social-tabs").dcSocialTabs({
    widgets: "twitter,facebook,fblike,fbrec,google,linkedin,rss",
    rssId: "http://feeds.feedburner.com/intensityjobs",
    twitterId: "#{AppConfig.get 'twitter.handler' }",
    facebookId: "#{AppConfig.get 'facebook.app_id' }",
    fblikeId: "#{AppConfig.get 'facebook.app_id' }",
    fbrecId: "http://www.intensityjobs.com",
    googleId: "#{AppConfig.get 'google_plus.app_id'}",
    linkedinId: 'http://www.linkedin.com/company/intensityjobs',
    location: 'bottom',
    align: 'bottom',
    offset: 30,
    width: 340,
    autoClose: true,
    start: 0})